name: "edsr"
type: "cnn"
epochs: 10000
batch_size: 1
save_steps: 1000
gen_steps: 1000

images:
  gt_size: 256
  channels: 3
  scale: 4

train:
  lr: !!float 1e-4
  lr_steps: [200000]
  lr_rate: 0.5
  num_filters: 64
  criterion: "l1"
  loss_weight: 1.0
  num_blocks: 8
  adam_beta1: 0.9
  adam_beta2: 0.99

datasets:
  train_datasets:
    FFHQ:
      path: "../datasets/FFHQ/"

  test_datasets:
    Celeba_HQ:
      path: "../datasets/Celeba_HQ_val/"

  test_size: 10
