net: "psnr_pretrain"
epochs: 1000
batch_size: 1
save_steps: 1000
gen_steps: 50

images:
  gt_size: 256
  channels: 3
  scale: 4

train:
  adam_beta1: 0.9
  adam_beta2: 0.99
  lr: !!float 2e-4
  lr_steps: [200000, 400000, 600000, 800000]
  lr_rate: 0.5
  pixel_criterion: "l1"
  pixel_weight: 1.0
  num_filters: 64
  num_blocks: 16

datasets:
  train_datasets:
    img_align_celeba:
      path: "../datasets/img_align_celeba/"

  test_datasets:
    img_align_celeba:
      path: "../datasets/img_align_celeba/"

  test_size: 10
