name: "srcnn"
type: "cnn"
epochs: 350000
batch_size: 1
save_steps: 10000
gen_steps: 1000

images:
  gt_size: 256
  channels: 3
  scale: 4

train:
  lr: !!float 1e-4
  lr_steps: [90000000]
  lr_rate: 1
  adam_beta1: 0.9
  adam_beta2: 0.99
  num_filters: 64
  criterion: "l1"
  loss_weight: 1.0

datasets:
  train_datasets:
    ImageNet:
      path: "../datasets/ImageNet/"

  test_datasets:
    DIV2K:
      path: "../datasets/DIV2K_valid_HR/"

  test_size: 10
