net: "srcnn"
type: "cnn"
epochs: 100
batch_size: 1
save_steps: 1000
gen_steps: 1

images:
  gt_size: 256
  channels: 3
  scale: 4

train:
  lr: !!float 1e-4
  num_filters: 64
  criterion: "l1"
  loss_weight: 1.0

datasets:
  train_datasets:
    img_align_celeba:
      path: "../datasets/img_align_celeba/"

  test_datasets:
    img_align_celeba:
      path: "../datasets/img_align_celeba/"

  test_size: 10
