name: "srgan_pretrain"
type: "cnn"
epochs: 200000
batch_size: 1
save_steps: 10000
gen_steps: 1000

images:
  gt_size: 256
  channels: 3
  scale: 4

train:
  adam_beta1: 0.9
  adam_beta2: 0.99
  lr: !!float 2e-4
  lr_steps: [100000]
  lr_rate: 0.1
  pixel_criterion: "l1"
  pixel_weight: 1.0
  num_filters: 64
  num_blocks: 16

datasets:
  train_datasets:
    FFHQ:
      path: "../datasets/FFHQ/"

  test_datasets:
    Celeba_HQ:
      path: "../datasets/Celeba_HQ_val/"

  test_size: 10
